version: ‘3.8’
services:
  rclone:
    container_name: rclone_vfs
    image: rclone/rclone
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=1002
      - PGID=1004
    volumes:
      - type: bind
        source: /DATA/DockerData/Plex/data
        target: /data
        bind:
          propagation: shared
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - /DATA/DockerData/Plex/rclone/config:/config/rclone
      - /DATA/DockerData/Plex/rclone/log:/log
      - /DATA/DockerData/Plex/rclone/cache:/cache
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    security_opt:
      - apparmor:unconfined
    command: "mount gd:Cloud   /data/mount    --allow-other --log-file /log/rclone.log --rc --rc-addr 0.0.0.0:5572 --log-level DEBUG --poll-interval 10s --umask 002 --drive-pacer-min-sleep 10ms --drive-pacer-burst 200 --vfs-cache-mode full --c>  plex:
    container_name: plexms
    image: horjulf/plex_autoscan
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=1002
      - PGID=1004
      - TZ=America/Chicago
      - HOSTNAME="Local-Arch"
      - VERSION=latest
      - PLEX_CLAIM=claim-SzFnW6AhYps6Bs7Nh3ze
    volumes:
      - type: bind
        source: /DATA/DockerData/Plex/data/mount
        target: /data
        bind:
          propagation: rslave
      - /DATA/DockerData/Plex/plexms/config:/config
<<<<<<< HEAD:Stream/docker-compose.yml
<<<<<<< HEAD
=======
      - /DATA/DockerData/Plex/data/mount:/data
>>>>>>> 9a9da15d8f1c9a32f5b7a300e2269001af16db11
=======
>>>>>>> 339310848a56087674cc6bfbb5b838e80f483f59:docker-compose.yml
